FROM golang:1.25-alpine

WORKDIR /app

RUN apk add --no-cache ca-certificates git bash
ENV PATH="/usr/local/go/bin:${PATH}"

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["sleep", "infinity"]
